'use strict';
const {test} = require('node:test');
const assert = require('node:assert/strict');
const M = require('../decision-model.js');
const fixture = changes => ({operations:3000,before:8,after:4,hourly:150,realization:100,monthly:5000,investment:100000,...changes});
test('blank inputs cannot produce a positive or negative ROI',()=>{const r=M.calculate({});assert.equal(r.ready,false);assert.equal(r.missing.length,7);assert.equal(r.payback,undefined);});
test('a single missing field prevents a fabricated assumption',()=>{for(const field of Object.keys(M.fields)){const r=M.calculate(fixture({[field]:''}));assert.equal(r.ready,false);assert.ok(r.missing.includes(field));}});
test('time and cash are distinct, with explicit recovery arithmetic',()=>{const r=M.calculate(fixture());assert.equal(r.hours,200);assert.equal(r.capacityValue,30000);assert.equal(r.cashGross,30000);assert.equal(r.cashNet,25000);assert.equal(r.payback,4);assert.equal(r.series[0].value,-100000);assert.equal(r.annualNet,200000);assert.equal(r.series.length,13);});
test('zero cash realization means time saved but no claimed cash savings',()=>{const r=M.calculate(fixture({realization:0}));assert.equal(r.hours,200);assert.equal(r.cashGross,0);assert.equal(r.cashNet,-5000);assert.equal(r.payback,null);assert.equal(r.annualNet,-160000);});
test('partial realization does not count all capacity as cash',()=>{const r=M.calculate(fixture({realization:25}));assert.equal(r.cashGross,7500);assert.equal(r.cashNet,2500);assert.equal(r.payback,40);});
test('negative time benefit is kept, not hidden by a zero clamp',()=>{const r=M.calculate(fixture({after:10}));assert.equal(r.hours,-100);assert.equal(r.cashNet,-20000);assert.equal(r.negativeTime,true);assert.equal(r.payback,null);});
test('equal times and zero recurring cost do not divide by zero',()=>{const r=M.calculate(fixture({after:8,monthly:0}));assert.equal(r.cashNet,0);assert.equal(r.payback,null);assert.equal(r.annualNet,-100000);});
test('zero upfront cost is not advertised as an infinite ROI',()=>{const r=M.calculate(fixture({investment:0}));assert.equal(r.hasInvestment,false);assert.equal(r.payback,null);assert.equal(r.annualNet,300000);});
test('negative and non-finite inputs are rejected',()=>{for(const k of Object.keys(M.fields))for(const n of [-1,NaN,Infinity,'Infinity','not a number',{},[]]){const r=M.calculate(fixture({[k]:n}));assert.equal(r.ready,false,k+': '+n);assert.ok(r.errors.length);}});
test('percentages above 100 and fractional operation counts are rejected',()=>{assert.equal(M.calculate(fixture({realization:101})).ready,false);assert.equal(M.calculate(fixture({operations:3.5})).ready,false);});
test('bounds are enforced for every field',()=>{for(const [k,f] of Object.entries(M.fields))assert.equal(M.calculate(fixture({[k]:f.max+1})).ready,false);});
test('decimal strings are accepted without implicit currency assumptions',()=>{const r=M.calculate(fixture({before:'8.5',after:'4.5',hourly:'150.25'}));assert.equal(r.hours,200);assert.equal(r.cashGross,30050);});
test('cash is rounded to cents and floating noise cannot create a payback',()=>{const r=M.calculate(fixture({operations:1,before:.01,after:0,hourly:.01,monthly:0}));assert.equal(r.cashGross,0);assert.equal(r.cashNet,0);assert.equal(r.payback,null);});
test('whitespace is missing input, not zero',()=>{assert.equal(M.calculate(fixture({investment:'  '})).ready,false);});
test('arithmetic never mutates user inputs or stores anything',()=>{const f=fixture();const before=JSON.stringify(f);M.calculate(f);assert.equal(JSON.stringify(f),before);});
test('monthly cashflow endpoint reconciles with annual net',()=>{for(const realization of [0,25,50,100])for(const monthly of [0,5000,50000]){const r=M.calculate(fixture({realization,monthly}));assert.equal(r.series.at(-1).value,r.annualNet);}});
